### ISSUE TITLE
Milestone: Thunderdome cost optimization

### ISSUE THREAD

**Issue by iand** [protocol/probelab#18]
eta: 2023-01-31

Children:
 - [x] Reduce the idle costs of Thunderdome infrastructure
 - [x] Reduce ingress costs of running an experiment
 - [x] Allow experiments to use smaller, cheaper instances
